name: 'tfsec'

on:
  workflow_dispatch:

jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: tfsec
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: ./
          args: --format=json --out=results.json

      - name: Upload tfsec results
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-results
          path: results.json 